name: "Production Deployment"

concurrency:
  group: habitica-integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint-and-build:
    name: "Lint & Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: yarn --frozen-lockfile
      - name: "Lint"
        run: yarn lint
      - name: "Build"
        run: |
          yarn core:build
          yarn github-app:build

  push-to-ecr:
    needs: [ 'lint-and-build' ]
    name: "Push to AWS ECR"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Extract metadata (tags, labels) for ECR"
        id: meta
        uses: docker/metadata-action@v5
      - name: "Log in to AWS ECR"
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_ACCESS_SECRET }}
      - name: "Build and push to ECR"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/habitica:${{ steps.meta.outputs.tags }}
          labels: |
            maintainer=${{ github.actor }}
            commit=${{ github.sha }}
