name: "Production Deployment"

concurrency:
  group: habitica-integration

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    name: "Build & Push Docker Image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: yarn --frozen-lockfile
      - name: "Lint"
        run: yarn lint
      - name: "Log in to the container registry"
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Extract metadata (tags, labels) for Docker"
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: "Build and push Docker image"
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-ionos:
    needs: [ 'build-and-push' ]
    name: "Deploy to IONOS"
    runs-on: ubuntu-latest
    steps:
      - name: 'Reload Docker Container'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            docker rm habitica-github-app-production
            docker image rm ghcr.io/drazenbebic/habitica-github-app:main
            docker pull ghcr.io/drazenbebic/habitica-github-app:main
            docker run -d \
              --name habitica-github-app-production \
              --network host \
              -e PORT='3002' \
              -e NODE_ENV='production' \
              -p 3002:3000 \
              ghcr.io/drazenbebic/habitica-github-app:main